fix(isubject): fix#15 won't compile
I added all the subject functions to bus because it won't compile otherwise.
I'm not sure why this isn't working. I'm now getting an undefined reference to
notify.  I'm just pushing so Brandon can clone this repo.